<Project>
  <PropertyGroup>
    <AppRawVersion Condition="'$(Version)' != ''">$(Version)</AppRawVersion>
    <AppRawVersion Condition="'$(AppRawVersion)' == '' and '$(APP_VERSION)' != ''">$(APP_VERSION)</AppRawVersion>
    <AppRawVersion Condition="'$(AppRawVersion)' == ''">0.1.0</AppRawVersion>
    
    <Version>$(AppRawVersion)</Version>
    <AssemblyVersion>$(AppRawVersion)</AssemblyVersion>
    <FileVersion>$(AppRawVersion)</FileVersion>
    <InformationalVersion>$(AppRawVersion)</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Product>Stream Helper</Product>
    <Company>Stream Helper</Company>
    <Authors>Vadim Lopatiuk</Authors>
    <Copyright>Copyright (c) 2026 Vadim Lopatiuk</Copyright>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <NuGetAudit>false</NuGetAudit>
    <NoWarn>$(NoWarn);NU1900</NoWarn>
    <ApplicationIcon Condition="Exists('$(MSBuildThisFileDirectory)assets\app.ico')">$(MSBuildThisFileDirectory)assets\app.ico</ApplicationIcon>
  </PropertyGroup>
</Project>
