<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <EnableMSTestRunner>true</EnableMSTestRunner>
    <NoWarn>$(NoWarn);MSTEST0037</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.0.2" />
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\StreamHelper.Shared\StreamHelper.Shared.csproj" />
    <ProjectReference Include="..\..\src\StreamHelper.Server\StreamHelper.Server.csproj" />
    <ProjectReference Include="..\..\src\StreamHelper.Client\StreamHelper.Client.csproj" />
  </ItemGroup>
</Project>
